import { createRequire } from 'node:module';
import fs from 'node:fs';
import { config } from '../server/config.js';
const require = createRequire('/Users/mingxia/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');
const { chromium } = require('playwright');
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1512, height: 1000 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const info = JSON.parse(fs.readFileSync('tmp/server.json'));
await page.goto(process.env.QA_URL || info.url);
await page.getByLabel('访问密码', { exact: true }).fill(config().password);
await page.getByRole('button', { name:'进入工作台' }).click();
await page.getByRole('heading', { name: '扬州 · 泰州 GEO 合作决策' }).waitFor();
await page.locator('.report-image img').first().waitFor();
await page.waitForFunction(() => [...document.querySelectorAll('.report-image img')].every(img => img.complete && img.naturalWidth > 0));
await page.screenshot({ path:'tmp/desktop.png', fullPage:true });
await page.getByRole('button', {name:'供应商对比',exact:true}).click();
await page.getByRole('tab',{name:'渠道与商业'}).click();
await page.getByText('29,400元为招商毛利；净利待核算',{exact:true}).waitFor();
await page.getByRole('button', {name:/资料与报告/}).click();
await page.getByRole('textbox',{name:'检索资料'}).fill('80%利润');
await page.locator('.search-result').first().waitFor();
await page.locator('.search-result').first().click();
await page.getByRole('dialog').waitFor();
await page.getByRole('button',{name:'关闭引用'}).click();
await page.getByRole('button',{name:'待核实事项',exact:true}).click();
await page.locator('.task input').first().check();
await page.locator('.task input').first().uncheck();
await page.getByRole('button',{name:'决策概览',exact:true}).click();
await page.locator('.consent input').click();
await page.getByRole('textbox',{name:'向决策助手提问'}).fill('帮我做一个炒菜食谱');
await page.getByRole('button',{name:'发送问题',exact:true}).click();
await page.getByText('这个入口仅处理 GEO 技术、供应商评估及扬州/泰州区域代理合作问题，暂不回答其他主题。',{exact:true}).waitFor();
await page.getByRole('button',{name:'新建对话'}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'tmp/mobile.png',fullPage:true});
await page.getByRole('button',{name:'打开决策助手'}).click();
await page.getByRole('textbox',{name:'向决策助手提问'}).waitFor({state:'visible'});
await page.waitForFunction(() => { const r = document.querySelector('.chat-panel').getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth + 1; });
await page.screenshot({path:'tmp/mobile-chat.png'});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
console.log(JSON.stringify({pageErrors:errors,overflow,speechInputButton:await page.getByRole('button',{name:'语音输入（浏览器识别服务）'}).count()}));
if(errors.length||overflow) throw new Error('Browser QA failed');
await browser.close();
