import assert from 'node:assert/strict';
import { config } from '../server/config.js';

const base = process.env.API_URL || 'https://qna-geo-api.supergokou-geo.workers.dev';
const origin = 'https://supergokou.github.io';
const request = (route, options = {}) => fetch(base + route, { ...options, signal: AbortSignal.timeout(70000) });
assert.equal((await request('/api/documents')).status, 401);
assert.equal((await request('/library.json')).status, 401);
assert.equal((await request('/api/session', { headers: { Origin: 'https://untrusted.example' } })).status, 403);
const preflight = await request('/api/chat', { method: 'OPTIONS', headers: { Origin: origin, 'Access-Control-Request-Headers': 'authorization,content-type' } });
assert.equal(preflight.status, 204);
assert.equal(preflight.headers.get('Access-Control-Allow-Origin'), origin);
const login = await request('/api/login', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: origin }, body: JSON.stringify({ password: config().password }) });
assert.equal(login.status, 200);
const { token } = await login.json();
assert(token);
const headers = { Authorization: `Bearer ${token}`, Origin: origin, 'Content-Type': 'application/json' };
const get = async route => { const r = await request(route, { headers }); assert.equal(r.status, 200, route); return r; };
const status = await (await get('/api/status')).json();
assert.equal(status.documents, 8);
assert.equal(status.pages, 182);
const hits = await (await get('/api/search?q=' + encodeURIComponent('迈富时80%利润'))).json();
assert(hits.length > 0);
const file = await get('/api/documents/brief/file');
assert.equal(Buffer.from(await file.arrayBuffer()).subarray(0, 5).toString(), '%PDF-');
const picture = await get('/api/previews/brief');
assert.equal(picture.headers.get('Content-Type'), 'image/webp');
await picture.arrayBuffer();
const chat = async question => {
  const r = await request('/api/chat', { method: 'POST', headers, body: JSON.stringify({ question, history: [], scope: 'all' }) });
  assert.equal(r.status, 200, 'Chat request failed');
  return r.json();
};
assert.equal((await chat('请给我做一份食谱')).mode, 'scope');
const started = Date.now();
const result = await chat('迈富时80%利润能直接作为我方净利润吗？');
assert.equal(result.mode, 'deepseek');
assert(result.citations.length > 0);
console.log(JSON.stringify({ accessProtection: 'passed', cors: 'passed', documents: status.documents, pages: status.pages, search: 'passed', pdf: 'passed', preview: 'passed', scopeRefusal: 'passed', model: result.model, durationMs: Date.now() - started, summary: result.summary, citations: result.citations.map(c => c.id) }, null, 2));
